<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Content;
use App\Models\Project;
use Illuminate\Database\Seeder;

class ContentSeeder extends Seeder
{
    /**
     * Each entry is [title, project title, category title (nullable)], already
     * cleaned of dev-workflow noise (DRAFT/OLD/COPY/FINAL/version tags) and
     * normalized to match the titles created by CategorySeeder/ProjectSeeder.
     *
     * @var array<int, array{0: string, 1: string, 2: ?string}>
     */
    private const array CONTENTS = [
        ['Client Testimonial Alpha', 'Marketing', 'Success Stories'],
        ['Case Study: ACME', 'Marketing Dept', 'Success Stories'],
        ['Case Study: ACME', 'Marketing', 'Success Stories'],
        ['API Docs Core', 'Dev Portal', 'Technical Guides'],
        ['Developer Manual - Authentication', 'Dev Portal', 'Technical Guides'],
        ['Q3 Summary - North America', 'Sales Ops Main', 'Sales Reports'],
        ['Revenue Archive 2023', 'Sales Ops Main', 'Sales Reports'],
        ['Success Case: Global Retail', 'Marketing', null],
        ['Sales 101: Training Deck', 'Global Revenue', 'Sales Reports'],
        ['Q4 Forecast', 'Global Revenue', 'Sales Reports'],
        ['Integration Guide', 'Alpha Research', 'Technical Guides'],
        ['Integration Guide', 'Alpha Research', 'Technical Guides'],
        ['Success Story: Fintech Partner', 'Marketing', 'Success Stories'],
        ['Client Testimonial - Beta', 'Customer Success', 'Success Stories'],
        ['Success Case: Logistics', 'Customer Success', 'Success Stories'],
        ['API Reference', 'Legacy Docs', null],
        ['Internal Dev Manual', 'Legacy Docs', 'Technical Guides'],
        ['Revenue Archive Q1', 'Sales Ops Main', 'Sales Reports'],
        ['Sales 101 Handbook', 'Sales Ops Main', 'Sales Reports'],
        ['Case Study: Healthcare', 'Marketing', 'Success Stories'],
        ['Client Testimonial', 'Marketing Dept', 'Success Stories'],
        ['Legacy API Docs', 'Dev Portal', 'Technical Guides'],
        ['Integration Snippets', 'Dev Portal', 'Technical Guides'],
        ['Q2 Sales Summary', 'Project Phoenix', 'Sales Reports'],
        ['Revenue Archive - July', 'Project Phoenix', 'Sales Reports'],
        ['Success Case: E-commerce', 'Marketing', 'Success Stories'],
        ['Case Study: E-commerce', 'Marketing Dept', 'Success Stories'],
        ['System Integration', 'Data Factory', 'Technical Guides'],
        ['Developer Manual', 'Data Factory', 'Technical Guides'],
        ['Sales 101 - West Coast', 'Sales Ops Main', 'Sales Reports'],
        ['Q1 Summary', 'Sales Ops Main', 'Sales Reports'],
        ['Success Case: Pharma', 'Customer Success', 'Success Stories'],
        ['Client Testimonial: Gamma', 'Customer Success', 'Success Stories'],
        ['API Docs - Webhooks', 'Dev Portal', 'Technical Guides'],
        ['Integration Guide', 'Dev Portal', 'Technical Guides'],
        ['Revenue Archive', 'Global Revenue', 'Sales Reports'],
        ['Sales 101 Mastery', 'Global Revenue', 'Sales Reports'],
        ['Migration Guide', 'Cloud Migration', 'Technical Guides'],
        ['Developer Manual - Cloud', 'Cloud Migration', 'Technical Guides'],
        ['Case Study: Education', 'Marketing', 'Success Stories'],
        ['Success Case - Schools', 'Marketing Dept', 'Success Stories'],
        ['API Docs - Rate Limits', 'Dev Portal', null],
        ['Sales Summary Q3', 'Project Phoenix', 'Sales Reports'],
        ['Revenue Archive Aug', 'Project Phoenix', 'Sales Reports'],
        ['Client Testimonial: Zeta', 'Marketing', 'Success Stories'],
        ['Success Case: Zeta Corp', 'Marketing Dept', 'Success Stories'],
        ['Developer Manual', 'Data Factory', 'Technical Guides'],
        ['Integration Checklist', 'Data Factory', 'Technical Guides'],
        ['Sales 101 - EMEA', 'Sales Ops Main', 'Sales Reports'],
        ['Q1 Summary - EMEA', 'Sales Ops Main', 'Sales Reports'],
        ['Case Study: Energy', 'Customer Success', 'Success Stories'],
        ['Client Testimonial: Wind', 'Customer Success', 'Success Stories'],
        ['API Docs', 'Alpha Research', 'Technical Guides'],
        ['Developer Manual', 'Alpha Research', 'Technical Guides'],
        ['Revenue Archive - Global', 'Global Revenue', 'Sales Reports'],
        ['Sales 101 - Advanced', 'Global Revenue', 'Sales Reports'],
        ['Success Case: Automotive', 'Marketing', 'Success Stories'],
        ['Case Study Auto', 'Marketing Dept', 'Success Stories'],
        ['Integration Notes', 'Legacy Docs', 'Technical Guides'],
        ['API Docs - Legacy Support', 'Legacy Docs', 'Technical Guides'],
        ['Q2 Summary Archive', 'Project Phoenix', 'Sales Reports'],
        ['Revenue Archive - Q2', 'Project Phoenix', 'Sales Reports'],
        ['Developer Manual', 'Cloud Migration', null],
        ['Migration Steps', 'Cloud Migration', 'Technical Guides'],
        ['API Docs', 'Data Factory', 'Technical Guides'],
        ['Integration - Factory', 'Data Factory', 'Technical Guides'],
        ['Success Case: Fashion', 'Marketing', 'Success Stories'],
        ['Client Testimonial - Style', 'Marketing Dept', 'Success Stories'],
        ['Developer Manual - SDK', 'Dev Portal', 'Technical Guides'],
        ['API Docs SDK', 'Dev Portal', 'Technical Guides'],
        ['Sales 101 - APAC', 'Sales Ops Main', 'Sales Reports'],
        ['Q1 Summary - APAC', 'Sales Ops Main', 'Sales Reports'],
        ['Case Study: Hospitality', 'Customer Success', 'Success Stories'],
        ['Success Case Hotel', 'Customer Success', 'Success Stories'],
        ['Integration Docs', 'Alpha Research', 'Technical Guides'],
        ['Developer Manual New', 'Alpha Research', 'Technical Guides'],
        ['Sales 101 Summary', 'Global Revenue', 'Sales Reports'],
        ['Revenue Archive Master', 'Global Revenue', 'Sales Reports'],
        ['Case Study: SaaS', 'Marketing', 'Success Stories'],
        ['Success Story SaaS', 'Marketing Dept', 'Success Stories'],
        ['Cloud API Docs', 'Cloud Migration', 'Technical Guides'],
        ['Developer Manual', 'Cloud Migration', 'Technical Guides'],
        ['Q3 Summary Forecast', 'Project Phoenix', 'Sales Reports'],
        ['Revenue Aug', 'Project Phoenix', 'Sales Reports'],
        ['Integration Guide', 'Data Factory', 'Technical Guides'],
        ['API Docs - Factory Core', 'Data Factory', 'Technical Guides'],
        ['Success Case: Real Estate', 'Marketing', 'Success Stories'],
        ['Client Testimonial RE', 'Marketing Dept', 'Success Stories'],
        ['Developer Manual', 'Dev Portal', 'Technical Guides'],
        ['API Docs - Security', 'Dev Portal', 'Technical Guides'],
        ['Revenue Archive', 'Sales Ops Main', 'Sales Reports'],
        ['Sales 101 Training', 'Sales Ops Main', 'Sales Reports'],
        ['Success Case: Fintech', 'Customer Success', 'Success Stories'],
        ['Client Testimonial', 'Customer Success', 'Success Stories'],
        ['Integration Flow', 'Alpha Research', 'Technical Guides'],
        ['API Docs - Endpoint List', 'Alpha Research', 'Technical Guides'],
        ['Q4 Summary', 'Global Revenue', 'Sales Reports'],
        ['Sales 101 - Q3 Edit', 'Global Revenue', 'Sales Reports'],
        ['Case Study: Travel', 'Marketing', 'Success Stories'],
        ['Success Case: Travel Air', 'Marketing Dept', 'Success Stories'],
        ['Developer Manual', 'Legacy Docs', 'Technical Guides'],
        ['API Reference 2', 'Legacy Docs', 'Technical Guides'],
        ['Revenue Summary Sep', 'Project Phoenix', 'Sales Reports'],
        ['Sales 101 - Phoenix Edition', 'Project Phoenix', 'Sales Reports'],
        ['Integration - Cloud', 'Cloud Migration', 'Technical Guides'],
        ['Migration Guide', 'Cloud Migration', 'Technical Guides'],
        ['Developer Manual - Production', 'Data Factory', 'Technical Guides'],
        ['API Docs Factory', 'Data Factory', 'Technical Guides'],
        ['Success Story: Food Chain', 'Marketing', 'Success Stories'],
        ['Case Study: Food', 'Marketing Dept', 'Success Stories'],
        ['Integration Map', 'Dev Portal', 'Technical Guides'],
        ['Developer Manual', 'Dev Portal', 'Technical Guides'],
        ['Q3 Summary - Revised', 'Sales Ops Main', 'Sales Reports'],
        ['Sales Guide', 'Sales Ops Main', 'Sales Reports'],
        ['Case Study: Logistics II', 'Customer Success', 'Success Stories'],
        ['Success Case: Cargo', 'Customer Success', 'Success Stories'],
        ['API Docs - Mobile', 'Alpha Research', 'Technical Guides'],
        ['Developer Manual Mobile', 'Alpha Research', 'Technical Guides'],
        ['Revenue Archive 2024', 'Global Revenue', 'Sales Reports'],
        ['Sales 101 - Digital', 'Global Revenue', 'Sales Reports'],
        ['Success Case: Gaming', 'Marketing', 'Success Stories'],
        ['Case Study Game', 'Marketing Dept', 'Success Stories'],
        ['Developer Manual - Core', 'Legacy Docs', 'Technical Guides'],
        ['API Docs Core 2', 'Legacy Docs', 'Technical Guides'],
        ['Q4 Summary Archive', 'Project Phoenix', 'Sales Reports'],
        ['Revenue Archive - Final Q4', 'Project Phoenix', 'Sales Reports'],
        ['API Integration', 'Cloud Migration', 'Technical Guides'],
        ['Developer Manual - Migration', 'Cloud Migration', 'Technical Guides'],
        ['Case Study: Pharma III', 'Marketing', 'Success Stories'],
        ['Success Story: Meds', 'Marketing Dept', 'Success Stories'],
        ['API Docs - GraphQL', 'Dev Portal', 'Technical Guides'],
        ['API Docs - GraphQL', 'Dev Portal', 'Technical Guides'],
        ['Sales 101 - Latin America', 'Sales Ops Main', 'Sales Reports'],
        ['Q2 Summary LatAm', 'Sales Ops Main', 'Sales Reports'],
        ['Client Story', 'Customer Success', 'Success Stories'],
        ['Success Case: Fin-Tech', 'Customer Success', 'Success Stories'],
        ['Integration Script', 'Alpha Research', 'Technical Guides'],
        ['Developer Manual - Alpha', 'Alpha Research', 'Technical Guides'],
        ['Revenue Archive - MidYear', 'Global Revenue', 'Sales Reports'],
        ['Sales Summary', 'Global Revenue', 'Sales Reports'],
        ['Case Study: AI Startup', 'Marketing', 'Success Stories'],
        ['Case Study: AI', 'Marketing Dept', 'Success Stories'],
        ['Integration Archive', 'Legacy Docs', 'Technical Guides'],
        ['Developer Manual - End of Life', 'Legacy Docs', 'Technical Guides'],
        ['Sales 101 - Phoenix Recap', 'Project Phoenix', 'Sales Reports'],
        ['Revenue Archive Nov', 'Project Phoenix', 'Sales Reports'],
        ['Migration Report', 'Cloud Migration', 'Technical Guides'],
        ['Developer Manual', 'Cloud Migration', 'Technical Guides'],
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projectIds = Project::query()->pluck('id', 'title');
        $categoryIds = Category::query()->pluck('id', 'title');

        foreach (self::CONTENTS as [$title, $projectTitle, $categoryTitle]) {
            Content::query()->create([
                'title' => $title,
                'project_id' => $projectIds[$projectTitle],
                'category_id' => $categoryTitle === null ? null : $categoryIds[$categoryTitle],
            ]);
        }
    }
}
